export const ADD_EXISTING_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const ADD_NON_EXISTING_ITEM_TO_CART = 'ADD_EXISTING_ITEM_TO_CART'
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
